/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppCaixaRouteImport } from './routes/_app/caixa'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppContasAPagarRouteImport } from './routes/_app/contas-a-pagar'
import { Route as AppContasAReceberRouteImport } from './routes/_app/contas-a-receber'
import { Route as AppDespesasRouteImport } from './routes/_app/despesas'
import { Route as AppLembretesRouteImport } from './routes/_app/lembretes'
import { Route as AppOrcamentoRouteImport } from './routes/_app/orcamento'
import { Route as AppPainelRouteImport } from './routes/_app/painel'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppRelatorioRouteImport } from './routes/_app/relatorio'
import { Route as AppVendasRouteImport } from './routes/_app/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCaixaRoute = AppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppContasAPagarRoute = AppContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppContasAReceberRoute = AppContasAReceberRouteImport.update({
  id: '/contas-a-receber',
  path: '/contas-a-receber',
  getParentRoute: () => AppRoute,
} as any)
const AppDespesasRoute = AppDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppRoute,
} as any)
const AppLembretesRoute = AppLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoRoute = AppOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioRoute = AppRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/caixa': typeof AppCaixaRoute
  '/clientes': typeof AppClientesRoute
  '/contas-a-pagar': typeof AppContasAPagarRoute
  '/contas-a-receber': typeof AppContasAReceberRoute
  '/despesas': typeof AppDespesasRoute
  '/lembretes': typeof AppLembretesRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/painel': typeof AppPainelRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorio': typeof AppRelatorioRoute
  '/vendas': typeof AppVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/caixa': typeof AppCaixaRoute
  '/clientes': typeof AppClientesRoute
  '/contas-a-pagar': typeof AppContasAPagarRoute
  '/contas-a-receber': typeof AppContasAReceberRoute
  '/despesas': typeof AppDespesasRoute
  '/lembretes': typeof AppLembretesRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/painel': typeof AppPainelRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorio': typeof AppRelatorioRoute
  '/vendas': typeof AppVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/caixa': typeof AppCaixaRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/contas-a-pagar': typeof AppContasAPagarRoute
  '/_app/contas-a-receber': typeof AppContasAReceberRoute
  '/_app/despesas': typeof AppDespesasRoute
  '/_app/lembretes': typeof AppLembretesRoute
  '/_app/orcamento': typeof AppOrcamentoRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorio': typeof AppRelatorioRoute
  '/_app/vendas': typeof AppVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/caixa'
    | '/clientes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/despesas'
    | '/lembretes'
    | '/orcamento'
    | '/painel'
    | '/produtos'
    | '/relatorio'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/caixa'
    | '/clientes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/despesas'
    | '/lembretes'
    | '/orcamento'
    | '/painel'
    | '/produtos'
    | '/relatorio'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/sitemap.xml'
    | '/_app/caixa'
    | '/_app/clientes'
    | '/_app/contas-a-pagar'
    | '/_app/contas-a-receber'
    | '/_app/despesas'
    | '/_app/lembretes'
    | '/_app/orcamento'
    | '/_app/painel'
    | '/_app/produtos'
    | '/_app/relatorio'
    | '/_app/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/caixa': {
      id: '/_app/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AppCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas-a-pagar': {
      id: '/_app/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof AppContasAPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas-a-receber': {
      id: '/_app/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/contas-a-receber'
      preLoaderRoute: typeof AppContasAReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/despesas': {
      id: '/_app/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AppDespesasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lembretes': {
      id: '/_app/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof AppLembretesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamento': {
      id: '/_app/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AppOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio': {
      id: '/_app/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AppRelatorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCaixaRoute: typeof AppCaixaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppContasAPagarRoute: typeof AppContasAPagarRoute
  AppContasAReceberRoute: typeof AppContasAReceberRoute
  AppDespesasRoute: typeof AppDespesasRoute
  AppLembretesRoute: typeof AppLembretesRoute
  AppOrcamentoRoute: typeof AppOrcamentoRoute
  AppPainelRoute: typeof AppPainelRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatorioRoute: typeof AppRelatorioRoute
  AppVendasRoute: typeof AppVendasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaixaRoute: AppCaixaRoute,
  AppClientesRoute: AppClientesRoute,
  AppContasAPagarRoute: AppContasAPagarRoute,
  AppContasAReceberRoute: AppContasAReceberRoute,
  AppDespesasRoute: AppDespesasRoute,
  AppLembretesRoute: AppLembretesRoute,
  AppOrcamentoRoute: AppOrcamentoRoute,
  AppPainelRoute: AppPainelRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatorioRoute: AppRelatorioRoute,
  AppVendasRoute: AppVendasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
